name: guess_song
description: "A fun music quiz game."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.1
  get_it: ^8.2.0
  dio: ^5.9.0

  # UI
  top_snackbar_flutter: ^3.3.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2

  # logger
  talker_flutter: ^5.0.0
  talker_dio_logger: ^5.0.0
  talker_riverpod_logger: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/splash/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
